version: '3'
networks:
 campus_virtual:

services:
  ud-observatorio-cliente:
     image: planesticud/ud-observatorio-cliente:latest
     container_name: ud-observatorio-cliente
     restart: on-failure
     env_file:
        - .env
     networks:
        - campus_virtual
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ud-observatorio-cliente.rule=Host(`observatorio.planestic.udistrital.edu.co`)"
      - "traefik.http.routers.ud-observatorio-cliente.tls=true"
      - "traefik.http.routers.ud-observatorio-cliente.tls.certresolver=le"
      - "traefik.http.services.ud-observatorio-cliente.loadbalancer.server.port=80"           
networks:
  campus_virtual:
    external: true
